### ISSUE TITLE
What is the image dataset?

### ISSUE THREAD

**Issue by finlay-liu** [Mylittlerapture/ConGAN#2]
Hi, Alex
It is nice work, good job. And could you tell more information about the image dataset?
thanks!

**Comment by volotat** [comment]
Well it's just small number of examples of images you want to generate. For the faces there was 100 random exaples of celebrity faces. For convenience, I dicede to put all images into one large image, here is examples of such images
https://github.com/Mylittlerapture/ConGAN/blob/master/shoes.png
https://github.com/Mylittlerapture/ConGAN/blob/master/faces.png
