### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by ghost** [Mylittlerapture/ConGAN#3]
Hi, great work on this I am getting this OSError while running this in google colab python3 gpu

![screen shot 2019-01-02 at 8 37 34 pm](https://user-images.githubusercontent.com/6818285/50620636-a2451900-0ece-11e9-9bdd-c7c281249c1c.png)

**Comment by ghost** [comment]
fixed by adding arial.tff font to repo

**Comment by Hunter8moon** [comment]
how to add a font?

**Comment by ghost** [comment]
search for arial.tff and download and upload or you can clone my fork which already has it

**Comment by Hunter8moon** [comment]
Thanks, all worked well. There is another question - how to run a trained network? I trained her, but the new launch repeats the training. How to save progress?

**Comment by Hunter8moon** [comment]
And how to remove the numbers from the output? Thanks for attention)

**Comment by ghost** [comment]
not sure I understand you can change save interval, which is set to 500, and it already saves the model right now. 

also try commenting out these lines for the numbers in congan.py

 d = ImageDraw.Draw(im)
            d.text((10,10), "{:.2f}".format(val) , font=fnt, fill=(255,255,255,255))  
            d.text((11,11), "{:.2f}".format(val) , font=fnt, fill=(0,0,0,255))
